name: Multi Job Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build karo
        run: echo "Code build ho raha hai..."

      - name: Build complete
        run: echo "Build complete!"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test karo
        run: echo "Tests chal rahe hain..."

      - name: Test complete
        run: echo "Sab tests pass ho gaye!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy karo
        run: echo "Deploying..."

      - name: Deploy complete
        run: echo "Application deploy ho gayi!"