name: Checkout Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout karo
        uses: actions/checkout@v4

      - name: Files dekho
        run: ls

      - name: Branch dekho
        run: git branch

      - name: Commit history dekho
        run: git log --oneline